a = "Croissant merde fois saucisson alors disruptif celui révolution révolution ouais ce vin vin. Non dans l'cul vin disruptif croissant fais chier du coup fais chier boulangerie. Épicé par car pouvoir apéro fais chier. Manger carrément ou frenchtech être grève boulangerie. Meilleur demander baguette très du coup baguette ouais. Dans l'cul fais chier comprendre omelette rester vin vin. Apéro vin putain pour meilleur. Croissant guillotine apéro fromage. Ce frenchtech comprendre apéro monde vin comme même il du coup depuis bière avec apéro. Épicé bière quand même merde. Venir voila saucisson pouvoir évidemment bien baguette il saucisson point dans l'cul du et paf le chien. Temps vin du coup.Leur manger meilleur car baguette. Merde ou dans l'cul déjà bière un boulangerie. Grand parce que cela disruptif frenchtech à la. Apéro ne fromage jour du coup ou dans l'cul baguette sur camembert putain meilleur. Ce guillotine faire omelette faire croissant à la. Révolution merde bière.     Manger le putain un putain. Boulangerie omelette apéro aucun à la. Son du avoir voila apéro vin voila omelette si manger.     Falloir putain meilleur grève. Avant guillotine peu bière à la croissant.     Si et aussi vin on baguette car. Ouais. Révolution disruptif voila mettre grève. Où manger même parce que depuis et paf le chien très ouais.     Il y a saucisson le carrément carrément comme même devoir baguette et car falloir meilleur.     Révolution ouais mon fromage révolution. Qui évidemment encore du coup et aussi sans camembert croissant ouais comprendre parce que mettre boulangerie du coup. Boulangerie rester fromage fromage.     Demander évidemment très et paf le chien faire à la vin parce que. Ce saucisson révolution à la. Il saucisson fais chier. Rester bière vin frenchtech.     Évidemment aucun boulangerie fromage il et paf le chien. Aussi guillotine personne fromage meilleur part grève vin parce que. Carrément monde croissant du coup du épicé.     Frenchtech par et aussi évidemment avec révolution. Sur et paf le chien lui évidemment épicé.     Sans car pouvoir omelette voila quand même par quand même avoir ouais. Carrément fais chier vin passer putain fais chier baguette.     Avant du coup ce du coup putain croissant du coup deux fais chier de boulangerie carrément voila croissant. Lui manger camembert carrément meilleur omelette et aussi.     Déjà carrément on baguette.     Dans du coup fromage parce que dont car. Faire grève heure du frenchtech aller comme même. Grand guillotine quand même.     Quand même révolution. Épicé fromage avec apéro du coup.     Apéro grand fais chier aucun guillotine grève. Bière comme même carrément. Vin croissant quand même fromage comprendre révolution évidemment suite et aussi ouais raison épicé. Voila il du coup. Fromage dans l'cul bon et aussi putain."
b = a.split(' ')
c = set([x for x in b if x != ''])
d = []
for word in list(c):
	p = word.replace('.','').lower()
	d.append(p)
		
# import csv
# with open('dictword.csv', mode='a') as file:
# 	   writer = csv.writer(file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
# 	   writer.writerow(list(c))
print(d)